services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  WechatWorkGroupWelcomeTemplateBundle\Controller\:
    resource: '../../Controller/'
  WechatWorkGroupWelcomeTemplateBundle\Repository\:
    resource: '../../Repository/'
  WechatWorkGroupWelcomeTemplateBundle\Service\:
    resource: '../../Service/'
    public: true
  WechatWorkGroupWelcomeTemplateBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    public: true
